prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Subscribed
    filters: is:open -author:@me repo:inductiveautomation/ia-workspaces
    limit: 50 # optional limit of rows fetched for this section
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open -author:@me repo:inductiveautomation/ia-workspaces
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        grow: true
        width: 10
        hidden: false
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - key: D
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen dev...{{.HeadRefName}}"
        '
    # - key: v
    #   command: >
    #     cd {{.RepoPath}} &&
    #     code . && # VSCode
    #     gh pr checkout {{.PrNumber}} prs: []
repoPaths:
  :owner/:repo: ~/Code/:repo # template if you always clone github repos in a consistent location
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
pager:
  diff: "less"
confirmQuit: false
